DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS pass;
DROP TABLE IF EXISTS comments;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL
);

CREATE TABLE pass(
    id INTEGER PRIMARY KEY,
    password TEXT NOT NULL,
    FOREIGN KEY (id) REFERENCES user(id)
);

CREATE TABLE posts(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY(author_id) REFERENCES user (id)
);

CREATE TABLE comments(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    post_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    reacted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    body TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES user (id),
    FOREIGN KEY(post_id) REFERENCES posts (id)
);